const { initializeApp } = require('firebase/app');
const { getFirestore, collection, getDocs, deleteDoc, doc } = require('firebase/firestore');
const config = require('./firebase-applet-config.json');
const app = initializeApp(config);
const db = getFirestore(app, config.firestoreDatabaseId || '(default)');

async function run() {
  const itemsSnap = await getDocs(collection(db, 'inventoryItems'));
  let items = [];
  itemsSnap.forEach(d => items.push({ id: d.id, ...d.data() }));
  
  console.log("Total items:", items.length);
  
  let withInvId = items.filter(i => i.id.startsWith('INV-'));
  let withoutInvId = items.filter(i => !i.id.startsWith('INV-'));
  console.log("Items with INV- IDs:", withInvId.length);
  console.log("Items with other IDs (auto-generated by Firestore):", withoutInvId.length);
  
  if (withoutInvId.length > 0) {
    console.log("Samples of real items:", withoutInvId.slice(0, 3).map(i => i.name));
  }

  const suppliersSnap = await getDocs(collection(db, 'fournisseurs'));
  let suppliers = [];
  suppliersSnap.forEach(d => suppliers.push({ id: d.id, ...d.data() }));
  
  console.log("Total suppliers:", suppliers.length);
  let demoSuppliers = suppliers.filter(s => s.id.startsWith('F00') || s.nom === 'Coop Fès Primeurs');
  let realSuppliers = suppliers.filter(s => !(s.id.startsWith('F00') || s.nom === 'Coop Fès Primeurs'));
  
  console.log("Demo suppliers count:", demoSuppliers.length);
  console.log("Real suppliers count:", realSuppliers.length);
  
  process.exit(0);
}
run();
